version: "3"

services:
  db:
    image: postgres:11-alpine
    hostname: db
    ports:
      - "5432:5432"
    env_file: db-variables.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
  web:
    build: .
    command: bash -c "uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    env_file:
      - .pgadmin.env
    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  postgres_data: